### ISSUE TITLE
Expected cost posting is sort of incomplete

### ISSUE THREAD

**Issue by jglathe** [MicrosoftDocs/nav-content#101]
Hi there,

at an inventory costing training, after explaining how it works, I almost immediatily got the question: "Why are there no expected costs for item charges?" That is quite right from an accountant's point of view. You could argue that the charges are negligible, but that's not always the case. For example, when the charges are part of the purchase pricing, like copper markup. You receive the goods, post expected cost, and these are (significantly) too low for this type of transaction. And it's not an immaterial transaction either.
So, as a proposal for future improvements, could you please add expected cost value entries for assigned item charges when shipping/receiving? That would increase consistency of the inventory costing, and it would make the product more useful.

with best regards

Jens Glathe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2ccece1-62ee-270b-cd61-5ab3cf7424ef
* Version Independent ID: d1613f1f-79ba-8750-ce7f-24be54189005
* Content: [Design Details - Expected Cost Posting - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/design-details-expected-cost-posting)
* Content Source: [dynamics-nav-app/design-details-expected-cost-posting.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/design-details-expected-cost-posting.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi jglathe,

Thank you for your feedback! You can suggest features like this for both Dynamics NAV and Dynamics 365 Business Central here: [https://experience.dynamics.com/ideas/](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central)

**Comment by jglathe** [comment]
Hi @edupont04 ,

the "product" label appears to be meaningless. I followed the link, wriggled through all the profile update pages, and found... another forum where ideas go to die? I have seen too many of these. Why not use github and some sort of AI to collect these automatically?

with best regards

Jens Glathe

**Comment by edupont04** [comment]
Hi Jens,

We use the product label here in the documentation repo as a way for us to keep track of what the various issues are really about. 

Features suggested on the Ideas site are automatically picked up and added to the product team's backlog if they reach a specific number of votes. That's why I and the rest of the writing team prefer to ask you to submit your feature requests on the Ideas site.

**Comment by jglathe** [comment]
Hi @edupont04 ,

I was obedient, searched for the appropriate similar idea, added a vote and a link / comment to it. Sounds not really optimized, though ;)

with best regards

Jens Glathe
