### ISSUE TITLE
Two links to madeira URL

### ISSUE THREAD

**Issue by hougaard** [MicrosoftDocs/nav-content#103]
The two linked blog posts in the first paragraph are no longer valid links...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453eac27-2441-aa10-0717-5b2b76b30473
* Version Independent ID: 30f67749-2da2-9b74-2ba0-64e47287476a
* Content: [Setting Up Tax Groups, Areas, and Jurisdictions in the US - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/localfunctionality/unitedstates/us-sales-tax)
* Content Source: [dynamics-nav-app/LocalFunctionality/UnitedStates/us-sales-tax.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/LocalFunctionality/UnitedStates/us-sales-tax.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Erik,
Thank you for your feedback! This has now been fixed here, and a fix is also on its way for Business Central.
