### ISSUE TITLE
I got to this page from a wrong link

### ISSUE THREAD

**Issue by markborges** [MicrosoftDocs/nav-content#113]
The name of this page is "design-details-reservation-order-tracking-and-action-messaging" but the title actually reads "Design Details: Reordering Policies".

I got to this page from a link on https://docs.microsoft.com/en-us/dynamics-nav-app/inventory-how-to-reserve-items - Link at bottom of page: Design Details: Reservation, Order Tracking, and Action Messaging

this seems to be incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38530e94-6bb2-8f8b-8e0d-c46bc4db72ff
* Version Independent ID: 232c9748-e79e-8ce4-6693-c993a6b65409
* Content: [Design Details - Reordering Policies - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/design-details-reservation-order-tracking-and-action-messaging)
* Content Source: [dynamics-nav-app/design-details-reservation-order-tracking-and-action-messaging.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/design-details-reservation-order-tracking-and-action-messaging.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
