### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/nav-content#119]
Hello, The following link appears to be broken since it points to Managing Inventory Costs

Design Details: Variance Managing Inventory Costs
https://docs.microsoft.com/en-us/dynamics-nav-app/finance-manage-inventory-costs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb84f066-003d-7bd5-f778-621106598f3d
* Version Independent ID: 4e5bbc4c-923d-76a3-a093-e6bdc02569fe
* Content: [Design Details - Cost Components - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/design-details-cost-components)
* Content Source: [dynamics-nav-app/design-details-cost-components.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/design-details-cost-components.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This has been fixed.
