### ISSUE TITLE
Multilanguage?

### ISSUE THREAD

**Issue by mitrov** [MicrosoftDocs/nav-content#12]
Hi

This is more a question than an issue. Do you have any best practice suggestions in regards to multilanguage support? Should we just create a dynamics-nav-app folder for every language and translate the content?

Best regards
Džoka Mitrov

**Comment by edupont04** [comment]
Hello again,
No, we have language-specific repos in GitHub. You can fork those as well - or create your own if you want a language that we don't currently support like Catalan, for example. Take a look at the German repo here:
https://github.com/MicrosoftDocs/nav-content.de-DE

**Comment by mitrov** [comment]
The folder https://github.com/MicrosoftDocs/nav-content.de-de/tree/master/dynamics-nav-app
looks quite empty :-)
From https://github.com/MicrosoftDocs/nav-content.de-de/pull/1 I can see that the filenames of the markdown files are in english but the content is in german. Good to know.

**Comment by edupont04** [comment]
Sorry, I forgot to say that you have to switch to the live branch in the localization repos: https://github.com/MicrosoftDocs/nav-content.de-de/tree/live/dynamics-nav-app
And yes, the filenames are the same across all languages, but the content is not.
