### ISSUE TITLE
Missing link?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/nav-content#121]
"For more information, see this topic." There is no hyperlink in the text, there is no link anywhere on the page that refers to this subject (Workflow User Group hierarchies). I am having trouble even finding a page anywhere in the doc that explains this topic.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d14d31ae-71e7-40b0-e620-59293e7d8e1d
* Version Independent ID: eb12b834-ab93-e847-3eba-9ff7e43bc693
* Content: [How to Set Up Workflow Users - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/across-how-to-set-up-workflow-users)
* Content Source: [dynamics-nav-app/across-how-to-set-up-workflow-users.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/across-how-to-set-up-workflow-users.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello David,
Thank you for your feedback! This will be fixed in the next doc update.
