### ISSUE TITLE
Incorrect Page ID

### ISSUE THREAD

**Issue by skmcavoy** [MicrosoftDocs/nav-content#125]
Report Settings is page 1560 not 1506 (Workflow Event Hierarchies)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b084a1a3-2747-c776-5996-b4649b92c215
* Version Independent ID: fb7e3bfa-6f6d-e5dc-dd94-3d9d192fc55a
* Content: [Apply and Modify Saved Settings on Reports - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/reports-saving-reusing-settings)
* Content Source: [dynamics-nav-app/reports-saving-reusing-settings.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/reports-saving-reusing-settings.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! I apologize for our delay in getting back to you, but this will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
