### ISSUE TITLE
How to reverse entry from General Ledger with Job No?

### ISSUE THREAD

**Issue by RutaSl** [MicrosoftDocs/nav-content#132]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 246d6ffc-1067-1a48-a6fb-2caa7b03d35c
* Version Independent ID: 95a9f5ca-f55e-67cf-32b3-f44f8a010016
* Content: [Undo a Posting by Posting a Reversing Entry - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/finance-how-reverse-journal-posting)
* Content Source: [dynamics-nav-app/finance-how-reverse-journal-posting.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/finance-how-reverse-journal-posting.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Closing as non-actionable.
