### ISSUE TITLE
Wrong reference to "Generate XML Port"

### ISSUE THREAD

**Issue by MarcusFabian** [MicrosoftDocs/nav-content#138]
[Enter feedback here]
In BC18 the described option to create XMLPort (AL-Code) from XML Schema doesn't exist anymore (or at least not at the position described).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f21158d-f498-3dc3-b6cb-7e74187730ec
* Version Independent ID: d6143b9c-a2c0-5f71-4945-6dbe5f981f63
* Content: [Create XMLports based on XML schemas - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions)
* Content Source: [dynamics-nav-app/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Please note that this article applies to Dynamics NAV 20198, not Dynamics 365 Business Central. The equivalent article for Business Central is here: https://docs.microsoft.com/dynamics365/business-central/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions
