### ISSUE TITLE
Alignment with CRONOS

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/nav-content#139]
Hi there.  

I'm trying to implement Business Central at the moment, and one area that is completely frustrating is Microsoft's method of cost accounting for inventory.  I believe it's great, but it's far more complex than Netsuite, and in another world compared to basic book keeping software.

I currently have a CRONOS account (original seeded with Microsoft) whiich doesn't align with the accounts in this example.  There's no way of downloading or accessing a PDF of the GL referred to here.  CRONOS appears to manage this process differently and your ISV's are doing it differently again (some are repeating the same mistake with COGS interim in the wrong location!).  It makes it extremely difficult to 'see' what microsoft intended for the inventory costing process.

Can you include a link on this page back to the 'current' (or whatever) General Ledger reference you are refering to so we can quickly 'see' where you are anticipating you put your transactions?  Out of the box, Cronos, the Default Company and some of your ISV's are putting things in very different places in the GL, so it's hard to decipher the exact intended functionality.

It's great functionality - just very very difficult to understand exactly how to implement it because all the models don't reflect your documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2ccece1-62ee-270b-cd61-5ab3cf7424ef
* Version Independent ID: d1613f1f-79ba-8750-ce7f-24be54189005
* Content: [Design Details - Expected Cost Posting - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/design-details-expected-cost-posting)
* Content Source: [dynamics-nav-app/design-details-expected-cost-posting.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/design-details-expected-cost-posting.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Chris,

Thank you for your feedback! I can see that you're talking about Dynamics 365 Business Central, but you submitted your feedback based on the article for Dynamics NAV 2018. Here's the link to the (identical) article for Business Central: https://docs.microsoft.com/dynamics365/business-central/design-details-expected-cost-posting

From your feedback, I suspect that you're trying to learn about _inventory costing_, not _cost accounting_. Is that correctly understood? Inventory costing is about keeping track of your running costs of producing/storing/selling inventory, both for relatively small businesses and pretty large businesses. Cost accounting is more closely associated with complex organizations where you want to track costs across departments or subcontractors, for example. I can't pretend to fully understand either module, but it boils down to "pick your poison", so to speak. 

The Inventory Costing functionality has not changed in many years and has remained pretty much the same through many product names. It's complicated stuff, and the design details described the functionality based on the demonstration data at the time, about 15 years ago. The numbers and names of G/L accounts have changed since that, but the example doesn't hinge on account numbers. 

Expected cost is an optional angle on inventory costing - in most cases, you'll pick [average cost](https://docs.microsoft.com/dynamics365/business-central/design-details-average-cost) as your way of calculating cost because it's simpler to understand. We don't have online training for inventory costing yet, unfortunately, but the design details do describe the module rather detailed: https://docs.microsoft.com/dynamics365/business-central/design-details-costing-methods

**Comment by chris7777au** [comment]
Hey Eva.

I’m running FIFO which should be fairly easy.  One of the issues is the fact that the documentation is 15 years old and Microsoft has shifted all the names!  Makes it really really difficult to pick apart.  Having a link to the En-US Demo GL may shine some light on what/where you have put things!)

You are correct – this is complex.  I have managed to work it out in everything from XERO to Netsuite and Oracle E.Business Suite (some time back)… Microsoft’s use of terms is really confusing and not the norm.

Is there a graphical page showing the entire account flow (referencing the names in the current Posting Setup pages) from P/O to S/O (purchase order to cash sale)?

I think the complexity gives you advantages… but only if we can drive it!

CRONOS should align with your help files…

Chris Pope
Pacsource Pty ltd
Unit 84, 1470 Ferntree Gully Road
Knoxfield, Victoria 3180, Australia
T. +61.3.9763.4500
M. +61.447.888.777
E. ***@***.******@***.***>

Disclaimer ; The information in this email including any attachments is confidential and may be legally privileged. If an addressing or transmission error has misdirected this email please notify the author by replying to this email and destroy the original message. If you are not the intended recipient, any use, disclosure, copying or distributions prohibited and may be unlawful. Distribution of this email to other parties may result in criminal prosecution.


From: Eva Dupont ***@***.***>
Reply to: MicrosoftDocs/nav-content ***@***.***>
Date: Thursday, 8 July 2021 at 4:53 pm
To: MicrosoftDocs/nav-content ***@***.***>
Cc: Chris Pope ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/nav-content] Alignment with CRONOS (#139)


Hello Chris,

Thank you for your feedback! I can see that you're talking about Dynamics 365 Business Central, but you submitted your feedback based on the article for Dynamics NAV 2018. Here's the link to the (identical) article for Business Central: https://docs.microsoft.com/dynamics365/business-central/design-details-expected-cost-posting

From your feedback, I suspect that you're trying to learn about inventory costing, not cost accounting. Is that correctly understood? Inventory costing is about keeping track of your running costs of producing/storing/selling inventory, both for relatively small businesses and pretty large businesses. Cost accounting is more closely associated with complex organizations where you want to track costs across departments or subcontractors, for example. I can't pretend to fully understand either module, but it boils down to "pick your poison", so to speak.

The Inventory Costing functionality has not changed in many years and has remained pretty much the same through many product names. It's complicated stuff, and the design details described the functionality based on the demonstration data at the time, about 15 years ago. The numbers and names of G/L accounts have changed since that, but the example doesn't hinge on account numbers.

Expected cost is an optional angle on inventory costing - in most cases, you'll pick average cost<https://docs.microsoft.com/dynamics365/business-central/design-details-average-cost> as your way of calculating cost because it's simpler to understand. We don't have online training for inventory costing yet, unfortunately, but the design details do describe the module rather detailed: https://docs.microsoft.com/dynamics365/business-central/design-details-costing-methods

**Comment by edupont04** [comment]
Hi Chris,

I've added this to our backlog to get fixed for Business Central. I expect to get someone to update the names and numbers of G/L accounts this summer, but I can't promise anything.

**Comment by chris7777au** [comment]
Ha.

Eva… it’s just nice to hear someone say that they will try!

This area is one area that is quite difficult to understand.  Sadly, there are many different ways Microsoft has used to describe some of the accounts and fields.  In one instance (it must have been in the earlier demo data) one of the ledgers was in the wrong location entirely (in the P&L, not the Balance sheet).  Inecta University picked this up in their training, but even some of the local Australian ISV’s still haven’t identified this.  So as a customer you are presented with many false ways of implementing a process and that is where it gets really confusing.  Microsoft does have documentation that states some of the fields, but doesn’t necessarily give you a clear example of where those accounts ‘should be’ in the G/L (in a real world example).   It would be great if you could have a help page that presents each of the fields in the general posting group setup, (i.e. Sales Account, … Purchase Payment Tollerance Credit Account… COGS Account, Purchase Account etc.) where (nominally) these ‘should’ be in the GL and a real world example of how transactions flow through (pictures please

Your supposed to be on summer holidays now yea?

Have a great day.
Cheers
Chris Pope
Pacsource Pty ltd
Unit 84, 1470 Ferntree Gully Road
Knoxfield, Victoria 3180, Australia
T. +61.3.9763.4500
M. +61.447.888.777
E. ***@***.******@***.***>

Disclaimer ; The information in this email including any attachments is confidential and may be legally privileged. If an addressing or transmission error has misdirected this email please notify the author by replying to this email and destroy the original message. If you are not the intended recipient, any use, disclosure, copying or distributions prohibited and may be unlawful. Distribution of this email to other parties may result in criminal prosecution.


From: Eva Dupont ***@***.***>
Reply to: MicrosoftDocs/nav-content ***@***.***>
Date: Thursday, 8 July 2021 at 5:53 pm
To: MicrosoftDocs/nav-content ***@***.***>
Cc: Chris Pope ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/nav-content] Alignment with CRONOS (#139)


Hi Chris,

I've added this to our backlog to get fixed for Business Central. I expect to get someone to update the names and numbers of G/L accounts this summer, but I can't promise anything.

**Comment by edupont04** [comment]
Closing as fixed for Dynamics 365 Business Central
