### ISSUE TITLE
See also link not formated correctly

### ISSUE THREAD

**Issue by ikoletic** [MicrosoftDocs/nav-content#48]
[How to: Export Payments to a Bank File](../..(payables-how-export-payments-bank-file.md)

---
#### Pojedinosti o dokumentu

⚠ *Nemojte uređivati ovu sekciju. Obavezno za docs.microsoft.com ➟ problem s povezivanjem na repozitoriju GitHub.*

* ID: 17972e6c-f1fe-b114-6779-457e306a7016
* Version Independent ID: 356e7668-e595-4682-fd2b-1b1b457d343a
* Content: [Electronic Funds Transfer (EFT) - Dynamics NAV App](https://docs.microsoft.com/hr-hr/dynamics-nav-app/localfunctionality/australia/electronic-funds-transfer-eft-)
* Content Source: [dynamics-nav-app/LocalFunctionality/Australia/electronic-funds-transfer-eft-.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/LocalFunctionality/Australia/electronic-funds-transfer-eft-.md)
* Service: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thanks! The fix will be included in our next push.

**Comment by edupont04** [comment]
Fixed and live here: https://docs.microsoft.com/en-us/dynamics-nav-app/localfunctionality/australia/electronic-funds-transfer-eft-
