### ISSUE TITLE
There are eight bin types.

### ISSUE THREAD

**Issue by cheims73** [MicrosoftDocs/nav-content#51]
Hi, in the table are only 6 bin types described. These are also the only ones we know. Could you please specify the other 2 bin types.
Thank you &
Best regards,

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b95cb-9580-0da4-c43a-58932730a15f
* Version Independent ID: 6af0e25b-7ca3-a668-20f6-aa0eb8e6de8a
* Content: [How to Set Up Bin Types - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/warehouse-how-to-set-up-bin-types#comments-container)
* Content Source: [dynamics-nav-app/warehouse-how-to-set-up-bin-types.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/warehouse-how-to-set-up-bin-types.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thanks for reporting this! We're investigating if the product supports 8 or 6 bin types and will provide an update here next week.

**Comment by SorenGP** [comment]
The topic has been changes to say "six" bin types.
