### ISSUE TITLE
Sentence fragment

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/nav-content#52]
I believe the line below is incomplete and should probably be similar to the following couple of lines.
Make sure that the job queue in your solution.

Make sure that the job queue in your installation is set up to handle workflow notifications, and that the Start Automatically From NAS check box is selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12bd6782-3076-cb3f-73ab-e66d3aa6217d
* Version Independent ID: cdb8ea99-5a17-b4c0-4bfd-0523cad05adf
* Content: [Setting Up Workflow Notifications - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/across-setting-up-workflow-notifications)
* Content Source: [dynamics-nav-app/across-setting-up-workflow-notifications.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/across-setting-up-workflow-notifications.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thanks! It is now fixed and will be available in a Help update shortly.
