### ISSUE TITLE
Step 6

### ISSUE THREAD

**Issue by meSimmons** [MicrosoftDocs/nav-content#58]
What do you do if the test fails with a time out ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525f4ac3-009b-61bb-48c7-0ad2d0982d4c
* Version Independent ID: 67fd4927-91fb-43b3-c147-f04d2895a496
* Content: [Setting up Email - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/madeira-how-setup-email#see-also)
* Content Source: [dynamics-nav-app/madeira-how-setup-email.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/madeira-how-setup-email.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi there,
That depends on your email settings. Depending on whether or not you are using Office 365 authentication, different things may be missing in your current settings in the SMTP Email Setup. Please contact your administrator for further guidance.
