### ISSUE TITLE
Add a link to multiple records

### ISSUE THREAD

**Issue by lodewijkvanderpol** [MicrosoftDocs/nav-content#60]
Hi,

Is it possible to add links to multiple items at once or more easily than manually to each item card?
We have multiple groups of 1000+ items which all need group specific document links on their item cards.

Hope someone has a suggestion. Many thanks in advance!

Best,
Lodewijk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b29208d-72dd-0d75-a4e7-02085b986f86
* Version Independent ID: 507ac1d0-d840-e154-b135-62fbd843def0
* Content: [How to Link from Records to External Information or Programs - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/ui-how-add-link-to-record)
* Content Source: [dynamics-nav-app/ui-how-add-link-to-record.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/ui-how-add-link-to-record.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hi there Lodewijk,
Thank you for your suggestion, but since it's a feature request, I suggest that you add it in the Collaborate tool (https://aka.ms/collaborate) or over on the Ideas site (https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1)

**Comment by lodewijkvanderpol** [comment]
Hi Eva,

Thanks for your reply. However, my suggestion is not a feature request. It
is a question whether this functionality is present in NAV or not, or if
someone has a workaround to achieve what it's needed.

Best, Lodewijk
