### ISSUE TITLE
We need a little more detail here...

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/nav-content#61]
"fill in the fields as necessary" would be sufficient if there were a link to documentation on how to create a column layout. But there is not. Can you please provide such a link here, as well as the requisite documentation?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c605046e-3fd1-df51-786d-e00d351fb72b
* Version Independent ID: 63ce011c-3705-2221-7a77-12512e3b3777
* Content: [Work with Account Schedules - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/bi-how-work-account-schedule)
* Content Source: [dynamics-nav-app/bi-how-work-account-schedule.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/bi-how-work-account-schedule.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic has been updated and will be available within approximately one week.
