### ISSUE TITLE
sales orders

### ISSUE THREAD

**Issue by heatherguinn** [MicrosoftDocs/nav-content#63]
Can this only be done on invoices, or can you also do this on sales orders as well? I don't see the option in the ribbon to get the standard sales codes.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6abf49be-2624-263b-463e-2001669c6e3b
* Version Independent ID: f2f4357b-5420-54a1-e1e9-f21a628ef0ce
* Content: [Setup and Use Standard Lines for Recurring Sales and Purchases - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/sales-how-work-standard-lines)
* Content Source: [dynamics-nav-app/sales-how-work-standard-lines.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/sales-how-work-standard-lines.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi - Yes, the Get Recurring Sales Lines action is also available from sales orders. I have updated the topic to make it clear that the feature is for all sales and purchase document types. 

Soren, Business Central writer

**Comment by LyleMurray** [comment]
I am not seeing the Get Recurring Sales Lines action on the  Sales Orders screen.  Is this available in NAV 2018 for Sales Orders?

**Comment by SorenGP** [comment]
Hi again - I now realize that you are on NAV, not on Business Central. Sorry about that. I have reported internally that the action is missing on sales orders. The fix will be available in a cumulative update for NAV 2018 as soon as possible.

**Comment by SorenGP** [comment]
PS: Help for NAV 2018 is no longer being updated. For updated help about Business Central, where approximately 95% of application features are the same as in NAV 2018, see https://docs.microsoft.com/en-us/dynamics365/business-central/.
