### ISSUE TITLE
Time Bucket not for Lot-For-Lot

### ISSUE THREAD

**Issue by chamusgilbert** [MicrosoftDocs/nav-content#65]
Time Bucket is blurred out for the Lot-for-Lot Reordering Policy. I'd love some information on the time fields that are related to Lot-for-Lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bae27c8-f72d-604b-5e14-593fd7c11dae
* Version Independent ID: 7cc5dce5-8c81-ecd6-4b2e-97b8837e6eda
* Content: [Design Details - Lot-for-Lot - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/design-details-lot-for-lot)
* Content Source: [dynamics-nav-app/design-details-lot-for-lot.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/design-details-lot-for-lot.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Planning fields that are not supported by a reordering policy are grayed (non-editable), such as the Time Bucket field for the Lot-for-Lot policy. 

All fields in Business Central are documented with tooltips in the UI. Hover over a field, such as an editable "time field" within the Lot-for-Lot reordering policy, to read a short description of its purpose.

This topic also describes the Lot-for-Lot reordering policy: https://docs.microsoft.com/en-us/dynamics-nav-app/design-details-planning-parameters
