### ISSUE TITLE
Custom report layout is ignored when printing multiple documents

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/nav-content#72]
For example, we create 2 custom report layouts for report 206 Sales Invoice. We now go to a customer's card and set a Custom Document Layout for it.

Now we go to the Posted Sales Invoices list, and we select multiple invoices to print. One of them must be of the customer were we defined to custom layout, and others don't need to have any custom layput defined.

Now when printing, the custom layput setting will be ignored or only one layout will be used for all invoices.

Seems like NAV cannot handle multiple layputs when printing several documents at the same time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa7e498f-b08f-194c-9e57-e80d55a87447
* Version Independent ID: 1a37caff-0644-9c55-e9a5-24c842e69fb2
* Content: [Create and Modify Custom Layouts for Reports and Documents - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/ui-how-create-custom-report-layout)
* Content Source: [dynamics-nav-app/ui-how-create-custom-report-layout.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/ui-how-create-custom-report-layout.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Closing this issue since it's about product functionality and not about the docs.

**Comment by averied** [comment]
Where shall I post this issue?
