### ISSUE TITLE
overconsumption of components on assembly line

### ISSUE THREAD

**Issue by Sander1908** [MicrosoftDocs/nav-content#79]
See point 7. in this how to 
Overconsumption of components in the quantity to consume does not work. The documentation is incorrect in relation to overconsumption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36365292-e6f1-43e9-451b-3dfb65eb5970
* Version Independent ID: 75973179-54b8-2c4a-eb07-dd0460f74a90
* Content: [How to Assemble Items - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/assembly-how-to-assemble-items#feedback)
* Content Source: [dynamics-nav-app/assembly-how-to-assemble-items.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/assembly-how-to-assemble-items.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you - The statement about over-consumption has bee removed. The updated topic will be available within one week.
