### ISSUE TITLE
Make Tax Digital content on NAV page - link to content for BC is still missing

### ISSUE THREAD

**Issue by dirkree** [MicrosoftDocs/nav-content#85]
Make Tax Digital content on NAV page - link to content for BC is still missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf57c939-4dab-7803-d67a-e3327d3b1249
* Version Independent ID: a9f8c532-da93-a2ca-0338-77e8e4e77455
* Content: [United Kingdom Local Functionality - Dynamics NAV App](https://review.docs.microsoft.com/en-us/dynamics-nav-app/localfunctionality/unitedkingdom/united-kingdom-local-functionality?branch=master)
* Content Source: [dynamics-nav-app/LocalFunctionality/UnitedKingdom/united-kingdom-local-functionality.md](https://github.com/MicrosoftDocs/nav-content/blob/master/dynamics-nav-app/LocalFunctionality/UnitedKingdom/united-kingdom-local-functionality.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by dirkree** [comment]
Any news on this?
Thanks

**Comment by dirkree** [comment]
Any news on this one, please?
Thanks
  Dirk

**Comment by dirkree** [comment]
Any news on this one, please?
Didn't we say … we add a link to the MTD help for BC here so partners can find at least something for MTD?

**Comment by SorenGP** [comment]
We are looking at updating NAV help with all or selected topics from BC help. For now, I had added the requested link. See the live topic.
