### ISSUE TITLE
update on documentation needed ?

### ISSUE THREAD

**Issue by dirkree** [MicrosoftDocs/nav-content#86]
do we need an update on the documentation, now that Elster is not supported in the same way as before anymore ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb85d2a6-17be-646f-4cf2-68257058b186
* Version Independent ID: e99e7d1d-ce06-d336-78fa-055dfbf348fc
* Content: [VAT Reporting - Dynamics NAV App](https://review.docs.microsoft.com/en-us/dynamics-nav-app/localfunctionality/germany/vat-reporting?branch=master)
* Content Source: [dynamics-nav-app/LocalFunctionality/Germany/vat-reporting.md](https://github.com/MicrosoftDocs/nav-content/blob/master/dynamics-nav-app/LocalFunctionality/Germany/vat-reporting.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Closing as this has been answered in email.
