### ISSUE TITLE
across-how-to-archive-documents (May be wording that used in help not so good)

### ISSUE THREAD

**Issue by finn777** [MicrosoftDocs/nav-content#90]
The feedback from the support case (Partner):
[https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-archive-documents](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-archive-documents)
![image](https://user-images.githubusercontent.com/16433990/52714163-3ca67b00-2faa-11e9-87c0-9086aa5ac27c.png)

Alexey (MS Supporter):
May be wording that used in help not so good.

In reality system just replace the existed Sales Order by archived version of the same order. 
Looks like return to saved game.

In reality, Restore Sales Order not possible after deleting original document.
System produce the message a-la:
Microsoft Dynamics 365 Business Central
"Unposted Order 1002 does not exist anymore.
It is not possible to restore the Order."

I’ve checked old version – NAV 2009 R2 (W1) (10 years ago version) - the same behavior.

This is according the design.
The old comment from DEV side:

*[http://vstfnav:8080/tfs/NAV/DynamicsNAVSE/_workitems?id=375008&triage=true&fullScreen=false&_a=edit](http://vstfnav:8080/tfs/NAV/DynamicsNAVSE/_workitems?id=375008&triage=true&fullScreen=false&_a=edit)

DynamicsNAVSE (375008): Restore Sales Quote not possible after deleting original document

This is clearly by design which the detailed error message illustrates.
The archive/restore functionality is there enable to restore to an earlier state while working with a particular document, When the document has been posted or the quote has been made into an order, restore is not possible anymore. This is a design decision.
*

**Comment by edupont04** [comment]
Hi Alexey,

Thanks for the suggestion to enhance the content. It would be great if you submitted a pull request with the proposed changes, though.

**Comment by finn777** [comment]
https://github.com/MicrosoftDocs/nav-content/pull/91

**Comment by edupont04** [comment]
Thanks! Closing issue :-)
