### ISSUE TITLE
Incorrect labeling?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/nav-content#98]
Can this be correct? Why would the Report Name be reversed from the Description?
"10411	Check (Stub/Check/Stub)	This report is designed to print checks in a check/stub/check format."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8447afc-29c0-5b5c-8255-fb31e937ac15
* Version Independent ID: b03f47ff-cc2e-562f-1715-8b700655f16f
* Content: [Specify the Layout of a Check - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/finance-how-define-check-layouts)
* Content Source: [dynamics-nav-app/finance-how-define-check-layouts.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/finance-how-define-check-layouts.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi buzzwick,

Thanks for your feedback! This has now been fixed.
